# Generated by Django 3.2.6 on 2021-08-13 19:49

from django.db import migrations, models
import webpage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario', models.CharField(max_length=80)),
                ('cantidad', models.IntegerField(null=True)),
                ('informacion', models.TextField(null=True)),
            ],
            bases=(models.Model, webpage.models.Mapa),
        ),
        migrations.CreateModel(
            name='Deforestacion',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('area', models.IntegerField()),
                ('cambio', models.IntegerField()),
            ],
            bases=(models.Model, webpage.models.Mapa),
        ),
    ]
